# Workflow to deploy a Shiny app to shinyapps.io
name: Deploy-Shiny

on:
  push:
    branches:
      - main

jobs:
  deploy-to-shinyapps:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # --- ADD THIS NEW STEP ---
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev

      - name: Install R package dependencies
        run: install.packages('rsconnect')
        shell: Rscript {0}

      - name: Deploy to shinyapps.io
        run: |
          rsconnect::setAccountInfo(
            name   = "${{ secrets.SHINYAPPS_ACCOUNT }}",
            token  = "${{ secrets.SHYAPPS_TOKEN }}",
            secret = "${{ secrets.SHINYAPPS_SECRET }}"
          )
          # Make sure to point to the correct app directory
          rsconnect::deployApp(
            appDir = "inst/shiny", # <-- ADD THIS LINE
            appName = "GIMP",
            forceUpdate = TRUE
          )
        shell: Rscript {0}
